services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn my_django_proj_17.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: my_django_proj_17.settings
      - key: PYTHON_VERSION
        value: 3.12


